<a href="https://colab.research.google.com/github/resnick1331/CursoIcaro_Python/blob/main/Copy_of_Clase_4_Python_%7C_ICARO_0525.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python - ICARO
_________________________________
Clase: 04  
Tema: Funciones y numpy
  
  
_________________________________


# Funciones

Repasamos el concepto e implementación de las funciones. Son un elemento fundamental en toda disciplina asociada a la prorgramación.  

Una función en python se define de la siguiente manera:


```
def nombre_de_la_función(parametro1, parametro2):
  ...
  bloque de código
  ...
  return algunValor # Opcional
```

Una función:   
* recibie 0 o tantos parámetros de entrada como necesitemos   
* ejecuta código definido en su interior de forma equivalente al resto de nuestras celdas.   
* opcionalmente, puede además retornar algún valor   

Para llamarla simplemente escribimos su nombre y le pasamos los parámetros que necesite (si es que necesita). Además, al terminar de ejecutarse "devuelve" algún valor en la línea que la llamó.  

Veamos algunos ejemplos:

In [ ]:
# Función que no recibe parámetros y no retorna ningún valor. En su interior,
# ejecuta una única línea. Llama a la función "print", que muestra en pantalla
# el texto entre paréntesis

def nuestra_funcion():
  print("Nuestra primer funcion que no retorna nada y simplemente imprime un mensaje")

In [ ]:
nuestra_funcion()

In [ ]:
# Función que recibe parámetros pero no retorna ningún valor

def otra_funcion(parametro):
  print(f"el parametro toma el valor: {parametro}")

otra_funcion("un valor")
otra_funcion(5)
otra_funcion([1,2,3])

In [ ]:
# Función que recibe parámetros y retorna un valor
def suma(a, b):
    return a+b

In [ ]:
c = suma(5, 6)
print(c)

##### Docstrings

Es una muy buena práctica, documentar lo que hacemos. Muchas veces otras personas van a ver nuestro código, nuestros análisis en notebooks, etc. No es simple ver el código de otra persona cuando no hay ningún comentario ni explicación.

Tenemos que acostumbrarnos desde ahora a comentar bien las funciones que hacemos y aprovechar las celdas de texto para explicar lo que vamos haciendo.

En python, una forma de describir lo que hace una función es usando "docstings". Esto es, una descripción que se pone entre 3 comillas """ al principio de la funcion. Por ejemplo:

In [ ]:
def suma(a, b):
  """
  Esta funcion retorna la suma de los valores de a y b.
  Params:
  - a: número a (int)
  - b: número b (int)
  """
  return a + b

Otra buena práctica, es especificar el tipo de dato que esperamos que reciba una función y el tipo de dato que devuelve. Esto se hace de la siguiente forma:

In [ ]:
# type hint
def suma(a: int = 5, b: int = 6) -> int:
  """
  Esta funcion retorna la suma de los valores de a y b.
  Params:
  - a: número a (int)
  - b: número b (int)
  """
  return a + b

Además, cuando definimos una función con docstings, al utilizar la funcion `help`de python, ¡ese docstring se imprime y puede ser muy util para otra persona que quiera usar nuestra función! También puedes probar este comando con cualquier otra función que utilices.

In [ ]:
help(suma)

Parametros por defecto

In [ ]:
def resta(a=None, b=None):
    if a == None or b == None:
        print("Error, debes enviar dos números a la función")
        return   # indicamos el final de la función aunque no devuelva nada
    else:
      return a-b

#resta()

In [ ]:
resta(5, 6)

# Ejercicios

1) Realiza una función llamada `relacion(a, b)` que a partir de dos números cumpla lo siguiente:

Si el primer número es mayor que el segundo, debe devolver 1.
Si el primer número es menor que el segundo, debe devolver -1.
Si ambos números son iguales, debe devolver un 0.


2) Realiza una función `separar(lista)` que tome una lista de números enteros y devuelva dos listas ordenadas. La primera con los números pares y la segunda con los números impares.



# Numpy

Recuerden que siempre pueden tener la documentación a mano cuando necesitan algo: https://numpy.org/doc/stable/

En esta clase vamos a empezar a aprender las principales funcionalidades que nos brinda numpy.

Lo primero que tenemos que hacer para usar una librería, es instalarla. Esto la disponibiliza en el sistema en que estemos corriendo nuestro código. En python, las librerías se pueden instalar con el comando `pip install NombreDeLaLibreria`. Siempre en la documentación de una librería nos van a explicar como instalarla.

Si usamos Google Colab, numpy ya viene instalado; lo hizo Google en sus servidores por nosotros. Si no, en un entorno local u otro, debemos correr el siguiente comando:

In [ ]:
pip install numpy

In [ ]:
!pip install numpy

Vemos que dice: Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (version)

Esto quiere decir que ya estaba instalada desde antes.

Una vez que instalada, tenemos que importarla. Es decir, además de estar disponible en nuestro sistema tenemos que avisar a la notebook o el entorno de ejecución que la vamos a usar en este programa. En python, esto se hace de la siguiente manera:

In [ ]:
import numpy as np

La parte que dice `as np` se denomina alias. Esto es para que cuando querramos llamar a la librería, no tengamos que poner su nombre completo y podamos llamarla simplemente con el alias `np`. En adelante, cuando veas funciones o elementos precedidos por `np`, sabrás que estamos accediendo a código incluído en la librería.

## Numpy array

El elemento principal de numpy es el numpy array. Para crear uno hay varias formas, una de ellas es pasándo una lista como parámetro:

In [ ]:
lista = [1,2,3,4]
numpy_array = np.array(lista)
print(lista)
print(numpy_array)

[1, 2, 3, 4]
[1 2 3 4]


En este caso, en el que el array esta compuesto por un rango de números en forma ascendente, numpy nos brinda formas más rapidas de crear un array:

In [ ]:
np.arange(4)
print(np.arange(5))

[0 1 2 3 4]


Este array empieza desde 0, nuestra lista anterior arrancaba desde 1. ¿ Cómo podremos hacer que el array arranque desde 1 ?
Para responder preguntas de este tipo, la documentación y el comando help() son muy útiles.

Veamos que dice el comando help:

In [ ]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.

    See the Warn

Ahora, tratemos de generar un array de 6 elementos que arranque desde el valor 0!

In [ ]:
nuevo_array = np.arange(6) # COMPLETAR
print(nuevo_array)

[0 1 2 3 4 5]


### Operaciones sobre listas y arrays de numpy

Otra funcionalidad muy útil que nos provee numpy, es la posibilidad de realizar una operación matemática sobre cada elemento de la lista de una forma muy simple.

Si queremos hacer esto con una lista común de python, vamos a necesitar iterar sobre cada elemento (con un for). Numpy nos ahorra ese paso:

In [ ]:
# Al hacerlo sobre una lista, vamos a obtener un error:

[1,2,3] + 1

TypeError: can only concatenate list (not "int") to list

In [ ]:
l = [1,2,3,4,5,6]
l_sum = []
for elem in l:
    elemento = elem + 1
    l_sum.append(elemento)
l_sum

[2, 3, 4, 5, 6, 7]

In [ ]:
# Si queremos hacerlo sobre una lista tenemos que usar list comprehension

l = [1,2,3,4,5,6]
l_sum = [item + 1 for item in l]
l_sum

[2, 3, 4, 5, 6, 7]

In [ ]:
# Pero sobre un numpy array, lo podemos hacer simplemente sumando un número:

np.arange(1,7) + 1

array([2, 3, 4, 5, 6, 7])

In [ ]:
np.arange(1,7) * 5

array([ 5, 10, 15, 20, 25, 30])

### Arrays multidimensionales

Al igual que las listas, los arrays de numpy pueden ser n-dimensionales

In [ ]:
n_dimensiones = np.array([[[1,2,3], [4,5,6]],
                          [[7,8,9], [10, 11, 12]]])

In [ ]:
n_dimensiones

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### Shape

Vimos que los arrays de numpy tienen un atributo que se llama `shape`. Esto nos dice la "forma" que tiene el array. Veamos un ejemplo:

In [ ]:
n_dimensiones.shape

(2, 2, 3)

El shape de un array puede modificarse con la función reshape() de numpy:

In [ ]:
una_dim = np.arange(5)
una_dim

array([0, 1, 2, 3, 4])

In [ ]:
una_dim.shape

(5,)

In [ ]:
# (filas, columnas)
una_dim = una_dim.reshape(5, 1)
una_dim

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
una_dim = una_dim.reshape(1, 5)
una_dim

### Linspace

La función linspace de numpy, nos permite crear arreglos de una forma similar a arange().

La diferencia con arange() es que en esta función, se crean n elementos igualmente espaciados en un intervalo que definamos.

Por ejemplo, si queremos crear un array de 10 elementos igualmente espaciados entre 0 y 1:

In [ ]:
np.linspace(0, 1, 10)

Recuerden que siempre se puede usar help!

In [ ]:
help(np.linspace)

Y también tenemos documentación: https://numpy.org/doc/stable/reference/generated/numpy.linspace.html

### Zeros y Ones

Numpy también nos permite crear un array de tantos 0s o 1s como querramos

In [ ]:
np.ones(10)

In [ ]:
np.zeros(10)

O podemos usar la función full() y crear un array con la shape y el valor que querramos:

In [ ]:
np.full(shape=(2,2), fill_value=3)

### Acceder a elementos del array

Al igual que una lista, para acceder a los elementos de un array de numpy podemos utilizar el indice de los elementos que querramos o un rango [start:stop:step]

In [ ]:
numpy_array

In [ ]:
numpy_array[1]

In [ ]:
numpy_array[0:3]

### Mask

Muchas veces vamos a tener arrays enormes con datos y queremos filtrarlos. Por ejemplo, de un array queremos obtener todos los números que sean menores a 10.

Para hacer esto en una lista de python, deberíamos iterar sobre toda la lista. Podemos evitarlo usando masks en numpy.

Las masks (o filtros booleanos) se definen como una condición, por ejemplo para el caso en el que queremos saber si un elemento es < 10:

`lista < 10`

Esto nos va a retornar otra lista (con el mismo shape que la lista a la que le aplicamos la mask) pero que va a contener los valores `True` y `False`.

True en los casos que se cumple la condición, False de lo contrario.


In [ ]:
lista_a_filtrar = np.arange(100).reshape(10, 10) # Creamos una lista de 100 elementos con shape (10, 10), es decir, 10 filas y 10 columnas
lista_a_filtrar

In [ ]:
# Definimos la Mask

mask = lista_a_filtrar < 10
mask

Ahora, la Mask nos retorna otra lista con valores booleanos, pero si queremos usar esto para filtrar (aplicar la mascara), ¿cómo hacemos?

Es simple, se define de la siguiente manera:

In [ ]:
lista_filtrada = lista_a_filtrar[mask]
lista_filtrada

Las máscaras no sirven solo para filtrar, también podemos asignar un valor a los elementos que cumplan la condición. Veamos un ejemplo: Reemplacemos todos los elementos que sean menores a 10 por el numero 10:

In [ ]:
lista_elementos = np.arange(20)
mask = lista_elementos < 10
lista_elementos[mask] = 10 # Asignamos el valor "menor" a todos los items que cumplen la condicion
lista_elementos

### Otras funciones

No podemos ver todas las funciones que nos brinda numpy en una clase, pero vamos a ver algunas de las más comunes ya que el resto tiene una sintaxis similar.

Si queremos sumar todos los elementos de un array:

In [ ]:
lista_a_filtrar.sum()

In [ ]:
lista_a_filtrar

En numpy, las funciones se pueden aplicar por "axis" (eje). Por ejemplo, podemos aplicar la función sum() sobre cada columna:

In [ ]:
# Por columnas

lista_a_filtrar.sum(axis=0)

O sobre cada fila:


In [ ]:
# Por filas

lista_a_filtrar.sum(axis=1)

# ¡A practicar!

Ahora que vimos algunas funcionalidades de numpy, vamos a resolver algunos problemas. ¡Recuerden modificar, romper y arreglar todo lo que quieran!

Probablemente necesiten buscar algo en la documentación o utilizar el comando help().


#### Ejercicio

Crear un array de 3x3 en el que todos sus valores sean `True` de la forma más simple posible

In [ ]:
trues_array = #COMPLETAR
trues_array

#### Ejercicio

Reemplazar todos los números impares del siguiente array por el valor -1

In [ ]:
arr = np.arange(0, 10)
mask = # COMPLETAR
# COMPLETAR

#### Ejercicio

Investigar las funciones vstack y hstack de numpy.

1) Concatenar los arrays a y b horizontalmente

2) Concatenar los arrays a y b verticalmente

Resultado esperado:

1)
```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```

2)
```
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
      [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```



In [ ]:
a = np.arange(10).reshape(2,5)
b = np.repeat(1, 10).reshape(2,5)

In [ ]:
print(a)

In [ ]:
print(b)

##### Ejercicio

¡Cómo podemos obtener la intersección entre dos arrays?

Investigar la función `intersect1d` y utilizarla para los siguientes arrays:

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:
# COMPLETAR

In [ ]:
# Salida esperada: array([2, 4])

# Pandas

Pandas es otra librería muy utilizada en el mundo data. El principal concepto detrás de Pandas es el DataFrame.

Un DataFrame es una estructura de datos en general con dos dimensiones en la cual se puede guardar datos de distintos tipos (como caracteres, enteros, valores de punto flotante, factores y más) en columnas. En un DataFrame se van a almacenar los datos con los que querramos trabajar.

Pandas nos provee muchas funciones para manipular datos en un DataFrame. Lo interesante sobre todo, es que podremos hacer operaciones y aplicar funciones por columna. Es decir, sin necesidad de iterar con uno o más ciclos for anidados. Computacionalmente, es una implementación mucho más optimizada: ahorra tiempo y capacidad de procesamiento. Asuntos como ese, son los que hay que resolver al hablar de "big data", y existen librerías más especializadas para grandes volúmenes. El primer paso en las vidas de todo profesional data, es pandas; servirá durante mucho tiempo antes de tener que recurrir a algo más.

Pandas corre sobre Numpy, de manera que hay muchas cosas en común


In [ ]:
import pandas as pd

Un DataFrame se puede crear por ejemplo, a partir de un archivo csv (caso más común).

Para eso, pandas nos provee la función read_csv.

Antes que nada, si estamos trabajando en google colab, debemos montar drive en nuestro notebook.

Una vez montado drive, debemos reemplazar el path al archivo:

In [ ]:
from google.colab import drive # La usamos para montar nuestra unidad de Google Drive
drive.mount('/content/drive') # Montamos nuestra unidad de Google Drive
iris_dataset = pd.read_csv('drive/MyDrive/.... /iris_dataset.csv') # Completar con la ruta del drive donde esta guardado el dataset + iris_dataset.csv"

In [ ]:
iris_dataset = pd.read_csv('iris_dataset.csv')

In [ ]:
iris_dataset

Lo que hicimos fue leer un archivo csv y meterlo dentro de un DataFrame de pandas. Este DataFrame tiene filas y columnas.

Cad columna tiene un tipo de dato. Esto podemos verlo con la función info()

In [ ]:
iris_dataset.info()

Nos dice que todas las columnas son del tipo float, a excepción de "species" que es del tipo "object".

Es importante tener en cuenta el tipo de datos de las columnas ya que de esto depende las operaciones que podemos hacer sobre las mismas.

El dataset que estamos usando (iris_dataset) es muy conocido, pueden googlear para saber más del mismo.


Otra función muy útil de los DataFrames es describe()


In [ ]:
iris_dataset.describe()

Describe, nos da datos estadísticos de nuesto DataFrame.

Un DataFrame, puede tener valores faltantes. Estos valores faltantes en pandas se representan como NaN.

Cuántos datos faltantes hay en este DataFrame?

In [ ]:
iris_dataset.isna().sum()

Ninguno! Este dataset no tiene datos faltantes (rara vez nos vamos a encontrar con datasets de este tipo)

También podemos aplicar funciones sobre una columna.

Para seleccionar una columna, utilizamos [].

In [ ]:
iris_dataset['sepal_length']

Que tipo de dato nos retorna esto?

In [ ]:
type(iris_dataset['sepal_length'])

Una "Series". Una series es el objeto que compone a los dataframes de pandas.

Este objeto es muy similar a los que es un array de Numpy (de hecho esta construido sobre el). La diferencia es que el objeto Series tiene etiquetas (labels), eso quiere decir que puede ser indexado por la etiqueta, y no solo por la posicion.

Si en lugar de obtener una Series, quiero un DataFrame, puedo hacerlo utilizando corchetes dobles:

In [ ]:
iris_dataset[['sepal_length']]

En este caso, puedo seleccionar todas las columnas que quiera

In [ ]:
iris_dataset[['sepal_length', 'sepal_width', 'species']]

Los DataFrames también tienen un atributo "columns":

In [ ]:
iris_dataset.columns

Y otro atributo index:

In [ ]:
iris_dataset.index

Podemos elegir cualquier columna como index:

In [ ]:
iris_dataset = iris_dataset.set_index('sepal_length')

Si nos arrepentimos, podemos resetear el index para que vuelva a ser numérico

In [ ]:
iris_dataset = iris_dataset.reset_index()

In [ ]:
iris_dataset

### Head, Tail y Sample

A veces tenemos DataFrames con muchisimos datos y no queremos imprimir todo en un notebook, simplemente algunas filas como ejemplo.

Para esto existen las funciones head(), tail() y sample()

In [ ]:
iris_dataset.head()

In [ ]:
iris_dataset.tail()

In [ ]:
iris_dataset.sample(5, random_state=42)

Cuál es la diferencia entre las 3?

#### loc e iloc

Pandas nos probee las funciones loc e iloc para acceder a sus datos.

Para que sirven?

Investigar

In [ ]:
iris_dataset.loc[1,['sepal_length']]

In [ ]:
iris_dataset.iloc[1,0]

## Valores faltantes

Vimos que por lo general en los datasets tienen datos faltantes. Datos faltantes puede haber por muchas razones (errores, no tenemos el dato, perdimos el dato, etc).

Muchas veces, necesitamos completar estos valores faltantes con alguna aproximación que no altere nuestros resultados.

Existen muchas formas de imputar valores a datos faltantes:

- Podemos usar la media o mediana (imputación univariante)
- Podemos usar un valor fijo (imputación univariante)
- Podemos descartar la fila con datos faltantes (observar que descartar sin ningún criterio puede hacer que perdamos muchos datos)
- Podemos completar el valor faltante en función de los valores de otras columnas (imputación multivariante)

Tenemos que tener en cuenta que siempre es importante entender el problema. En datascience vamos a ver que muchas decisiones que tomemos DEPENDEN DEL PROBLEMA y son muy importantes ya que pueden alterar nuestros resultados finales.

En esta clase, vamos a trabajar con un dataset de review de vinos.

Lo podemos descargar en: https://www.kaggle.com/zynicide/wine-reviews/ (nos tenemos que registrar)

Si usan colab, recuerden subir el csv a drive y montar drive para poder leerlo con pandas.

In [ ]:
import pandas as pd

In [ ]:
wine_reviews_df = pd.read_csv('winemag-data_first150k.csv')

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
# wine_reviews_df = pd.read_csv('/content/drive/MyDrive/Curso DS/datasets/winemag-data_first150k.csv')

Exploremos un poco el dataset.

Imprimimos las primeras 5 filas:

In [ ]:
wine_reviews_df.head()

¿ Cuántas filas tiene el dataset? ¿ Y cuántas columnas ?

Esta pregunta, podemos responderla utilizando `shape`



In [ ]:
wine_reviews_df.shape

Vemos que el dataset tiene 150930 filas y 11 columnas.

¿ Cuántos valores faltantes tiene el dataset en cada columna ?

In [ ]:
wine_reviews_df.isna().sum()

Ahora, ¿Qué hacemos con los faltantes?

Pandas tiene el método .fillna() para imputar valores faltantes y el método .dropna() para eliminar filas con valores faltantes.

Veamos un poco de documentación:

In [ ]:
help(pd.DataFrame.dropna)

In [ ]:
help(pd.DataFrame.fillna)

Ahora, para no modificar nuestro dataset original, lo vamos a clonar

In [ ]:
df = wine_reviews_df.copy()

Ahora vamos a trabajar sobre df.

In [ ]:
df.isna().sum()

In [ ]:
df.info()

Vemos que las columnas que tienen datos faltantes son designation, price, region_1 y region_2.

Por ahora, como solo estamos aprendiendo Pandas, no vamos a explorar mucho los datos para tomar decisiones. Simplemente vamos a aprender como se usa pandas. En próximas clases vamos a empezar a explorar los datos con mas detalle para tomar buenas decisiones.

Empecemos con el método fillna:

Vamos a imputar los valores faltantes de la columna "price" con la media de la columna.

In [ ]:
mean_price = df['price'].mean()
df['price'] = df['price'].fillna(mean_price)

Verificamos que no haya más nulos

In [ ]:
df.isna().sum()

Vemos que ahora hay 0 null values en la columna price

Ahora, completemos las columnas "designation", "region_1" y "region_2" con el valor por defecto: "dato faltante".

Podemos hacerlo pasandole un diccionario como parametro:

In [ ]:
default_value = "dato faltante"
df = df.fillna(value={'designation': default_value, "region_1": default_value, "region_2": default_value})

In [ ]:
df.isna().sum()

Ahora nos queda la columna country. En este caso, lo que vamos a hacer es descartar las filas que tengan valores faltantes en esta columna.

Para esto, vamos a usar el método dropna() y vamos a pasarle el parámetro axis=0

Veamos cuantas filas tiene el dataset antes de borrar nulos:

In [ ]:
df.shape[0]

Borramos nulos:

In [ ]:
df = df.dropna(axis=0)

Y ahora debería haber 5 filas menos:

In [ ]:
df.shape[0]

In [ ]:
df.isna().sum()

## Filtro por máscara

Vimos que en numpy podemos utilizar filtros. En pandas también podemos hacerlo y es algo que vamos utilizar mucho asique es importante aprender a usarlo bien!

Los filtros se utilizan igual que en numpy.

Seleccionemos todas las filas en las que country sea = 'US'

In [ ]:
df[df['country'] == 'US']

## Correlación

Pandas nos provee una función para medir la correlación entre variables numéricas

In [ ]:
df[['points', 'price']].corr()

#### Ejercicio

Investigar las funciones:
- value_counts
- unique
- nunique
- max
- min
- sort_values

Responder las siguientes preguntas utilizando lo que sabemos de pandas + lo que investigamos de las funciones de arriba (con la menor cantidad de funciones posibles):

a) ¿ Qúe valores distintos (únicos) hay en la columna country ?

b) ¿ Cuántos valores distintos hay en la columna country ?

c) ¿ Con qué frecuencia (cuantas veces) aparece cada uno de los paises ?

d) ¿ Cuál es el valor máximo de la columna price ?

e) ¿ Cuál es el valor mínimo de la columna price ?

f) ¿ Cuál es el vino más caro ?

g) ¿ Cuántos vinos tienen un precio por encima de la media ?


# Apply

El método apply de los dataframes de pandas, nos permite realizar una acción sobre cada fila o columna (sobre un "axis") del dataset.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html

Por ejemplo, queremos crear una nueva columna que se llame "description_len" y contenga la cantidad de caracteres que hay en cada fila de la columna "description".

Primero: Definamos una función que cuente los caracteres de un string:

In [ ]:
def count_string_len(string:str) -> int:

    """
    La función retorna un número entero con la cantidad de caracteres del string.
    """
  # COMPLETAR

In [ ]:
df['description_len'] = df['description'].apply(count_string_len)

In [ ]:
df.head()

Para utilizar apply, no hace falta definir una función aparte. También podemos hacerlo directamente utilizando funciónes "lambda":

In [ ]:
df['description_len'] = df['description'].apply(lambda x: len(x))

In [ ]:
df.head()

#### Ejercicio: Utilizar una función lambda para crear una nueva columna que se llame float_point y contenga los mismos datos que la columna "points" pero en formato float

# Group by


La función group by de pandas, nos permite agrupar dataframes a partir de una o más columnas y mediante funciones de agregación obtener insights de cada grupo.

Veamos ejemplos:

In [ ]:
group_by_country = df.groupby('country')

In [ ]:
group_by_country

Vemos que groupby nos devuelve un objeto pandas.core.groupby.generic.DataFrameGroupBy.

Sobre este objeto, podemos aplicar directamente funciones de agregación como .count(), .sum(), .mean(), etcétera:

In [ ]:
group_by_country.count().head()

In [ ]:
group_by_country.mean()

¿ Por qué cuando aplicamos la función mean solo nos trae 4 columnas y el indice ?

También podemos agrupar por múltiples columnas:

In [ ]:
group_by_country_prov = df.groupby(['country', 'province'])
group_by_country_prov.mean().head()

Y si no queremos que las variables por las que agrupamos se conviertan en indices y sean una columna más, podemos especificarlo en la función:

In [ ]:
group_by_country_prov = df.groupby(['country', 'province'], as_index=False)
group_by_country_prov.sum().head()

Finalmente, también podemos aplicar distintas funciones de agregación a cada columna.

EJERCICIO: Averiguar como podemos aplicar una función de agregación distinta a cada columna y:

1) Agrupar el dataset por pais
2) Obtener una columna que tenga el precio medio por país y otra que contenga la sumatoria de puntos. (.mean() y .sum() ).

# Sort values

Para ordenar un dataframe de pandas, podemos utilizar la función sort_values()

EJERCICIO:

Ordenar el dataset por "points" de manera descendente.

In [ ]:
help(pd.DataFrame.sort_values)

------ ¡Fin de notebook! ------